"""create service requests table

Revision ID: 4d752a829946
Revises: 
Create Date: 2026-07-25 12:44:45.099441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d752a829946'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('new', 'drafted', 'approved', 'rejected', 'sent', name='service_request_status'), server_default='new', nullable=False),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('approved_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_requests'))
    )
    op.create_index(op.f('ix_service_requests_telegram_chat_id'), 'service_requests', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_service_requests_telegram_user_id'), 'service_requests', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_requests_telegram_user_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_telegram_chat_id'), table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
