"""add telegram update id

Revision ID: d0ab2103b288
Revises: fb5f85543783
Create Date: 2026-07-25 14:32:10.507601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ab2103b288'
down_revision: Union[str, Sequence[str], None] = 'fb5f85543783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('telegram_update_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(op.f('uq_service_requests_telegram_update_id'), 'service_requests', ['telegram_update_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_service_requests_telegram_update_id'), 'service_requests', type_='unique')
    op.drop_column('service_requests', 'telegram_update_id')
    # ### end Alembic commands ###
